# Generated by Django 2.1.1 on 2018-09-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='votes',
            new_name='up_votes',
        ),
    ]
